# Generated by Django 4.1.3 on 2022-12-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmaster',
            name='completed',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='ticketmaster',
            name='event_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ticketmaster',
            name='saveCurrent',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='ticketmaster',
            name='saveFuture',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketmaster',
            name='isFavorite',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
