# Generated by Django 4.1.3 on 2022-12-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0002_ticketmaster_completed_ticketmaster_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmaster',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
