# Generated by Django 4.1.3 on 2022-12-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0002_nps_completed_nps_park_id_nps_savecurrent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nps',
            name='image_url',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
