# Generated by Django 4.1.3 on 2022-12-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0003_nps_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='nps',
            name='event_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
