# Generated by Django 4.1.4 on 2022-12-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0004_nps_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nps',
            old_name='park_id',
            new_name='parkCode',
        ),
    ]
