# Generated by Django 4.1.4 on 2022-12-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0005_rename_park_id_nps_parkcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nps',
            name='state',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='nps',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='nps',
            name='type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='nps',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
