# Generated by Django 4.1.4 on 2023-01-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0007_alter_nps_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nps',
            old_name='user',
            new_name='user_id',
        ),
    ]
