# Generated by Django 4.1.4 on 2023-01-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0008_rename_user_nps_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nps',
            old_name='user_id',
            new_name='user',
        ),
    ]
