# Generated by Django 4.1.3 on 2022-12-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0002_yelp_business_id_yelp_completed_yelp_savecurrent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelp',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
