# Generated by Django 4.1.4 on 2022-12-20 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yelp', '0003_alter_yelp_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yelp_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('name', models.CharField(default=0, max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=250)),
                ('categories', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
