# Generated by Django 4.1.4 on 2022-12-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0004_yelp_api'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yelp_API',
        ),
    ]
